services:
    letterboxd-sync:
        image: ghcr.io/choff3/letterboxd-sync:latest
        environment:
            - REDIS_URL=redis://redis:6379
            - LETTERBOXD_USERNAME=''
            - PLEX_TOKEN=''
            - PLEX_HOST=''
        depends_on:
            - redis
            - letterboxd-list
    letterboxd-list:
        image: screeny05/letterboxd-list-radarr:latest
        environment:
            - REDIS_URL=redis://redis:6379
        depends_on:
            - redis
    redis:
        image: redis:6.0